CREATE TABLE CHINHANH
(
    MSCN VARCHAR(10) PRIMARY KEY,
    TENCN NVARCHAR(30)
);

CREATE TABLE NHANVIEN
(
    MSNV VARCHAR(10) PRIMARY KEY,
    HO NVARCHAR(30),
    TEN NVARCHAR(30),
    NGAYSINH DATE,
    NGAYVAOLAM DATE,
    MSCN VARCHAR(10),
    FOREIGN KEY (MSCN) REFERENCES CHINHANH (MSCN)
);

CREATE TABLE KYNANG
(
    MSKN VARCHAR(10) PRIMARY KEY,
    TENKN NVARCHAR(30)
);

CREATE TABLE NV_KN
(
    MSNV VARCHAR(10) REFERENCES NHANVIEN (MSNV),
    MSKN VARCHAR(10) REFERENCES KYNANG (MSKN),
    MucDo TINYINT,
    PRIMARY KEY (MSNV, MSKN)
);