-- cau 1
SELECT c.MATSX, HO + ' ' + TEN AS HoTen, NGAYSINH, PHAI FROM CONGNHAN c
JOIN TOSX ON c.MATSX = TOSX.MATSX
ORDER BY TENTSX, TEN

-- cau 2
SELECT TenSP, Ngay, SoLuong, (SOLUONG * TIENCONG) as ThanhTien FROM SANXUAT	s
JOIN SANPHAM sp ON sp.MASP = s.MASP
JOIN CONGNHAN c ON c.MACN = s.MACN
WHERE HO=N'Nguyễn Trường' AND TEN=N'An'
ORDER BY Ngay

-- cau 3
SELECT * FROM CONGNHAN cn
WHERE MACN NOT IN (
	SELECT MACN FROM SANXUAT sx
	JOIN SANPHAM sp ON sp.MASP = sx.MASP
	WHERE sp.TENSP=N'Bình gốm lớn'
)

-- cau 4
SELECT cn.MACN, cn.HO, cn.TEN, cn.PHAI, cn.NGAYSINH, cn.MATSX FROM CONGNHAN cn
JOIN SANXUAT sx ON cn.MACN = sx.MACN
JOIN SANPHAM sp ON sx.MASP = sp.MASP
WHERE sp.TENSP IN (N'Nồi đất', N'Bình gốm nhỏ')
GROUP BY cn.MACN, cn.HO, cn.TEN, cn.PHAI, cn.NGAYSINH, cn.MATSX
HAVING COUNT(DISTINCT sp.TENSP) = 2;

-- cau 5
SELECT TENTSX, COUNT(cn.MACN) AS SoLuongCongNhan FROM TOSX t
LEFT JOIN CONGNHAN cn ON t.MATSX = cn.MATSX
GROUP BY t.MATSX, t.TENTSX -- Nhom tat ca cac cong nhan lai theo tung to sx

-- cau 6
SELECT HO, TEN, sp.TENSP, 
	SUM(sx.SOLUONG) AS TongSLThanhPham,
    SUM(sx.SOLUONG * sp.TIENCONG) AS TongThanhTien 
FROM CONGNHAN cn
JOIN SANXUAT sx ON sx.MACN = cn.MACN
JOIN SANPHAM sp ON sp.MASP = sx.MASP
GROUP BY cn.MACN, cn.HO, cn.TEN, sp.MASP, sp.TENSP
ORDER BY cn.TEN, sp.TENSP;

-- cau 7
SELECT SUM(sx.SOLUONG * sp.TIENCONG) AS TongTienCongThang1_2007 
FROM SANXUAT sx
JOIN SANPHAM sp ON sx.MASP = sp.MASP
WHERE YEAR(sx.NGAY) = 2007 AND MONTH(sx.NGAY) = 1;

-- cau 8
SELECT TOP 1 WITH TIES
    sp.TENSP,
    SUM(sx.SOLUONG) AS TongSoLuong
FROM SANXUAT sx
JOIN SANPHAM sp ON sx.MASP = sp.MASP
WHERE YEAR(sx.NGAY) = 2007 AND MONTH(sx.NGAY) = 2
GROUP BY sp.MASP, sp.TENSP

-- cau 9
SELECT TOP 1 WITH TIES
    cn.HO + ' ' + cn.TEN AS HoTen,
    SUM(sx.SOLUONG) AS TongSoChen
FROM CONGNHAN cn
JOIN SANXUAT sx ON cn.MACN = sx.MACN
JOIN SANPHAM sp ON sx.MASP = sp.MASP
WHERE sp.TENSP = N'Chén'
GROUP BY cn.MACN, cn.HO, cn.TEN
ORDER BY TongSoChen DESC;

-- cau 10
SELECT ISNULL(SUM(sx.SOLUONG * sp.TIENCONG), 0) AS TienCongThang2_2006 FROM SANXUAT sx
JOIN SANPHAM sp ON sx.MASP = sp.MASP
WHERE sx.MACN = 'CN002' AND YEAR(sx.NGAY) = 2006 AND MONTH(sx.NGAY) = 2;

-- cau 11
SELECT c.HO, c.TEN, COUNT(DISTINCT sx.MASP) AS SoLoaiSanPham FROM CONGNHAN c
JOIN SANXUAT sx ON c.MACN = sx.MACN
GROUP BY c.MACN, c.HO, c.TEN
HAVING COUNT(DISTINCT sx.MASP) >= 3;

-- cau 12
UPDATE SANPHAM
SET TIENCONG = TIENCONG + 1000
WHERE TENSP LIKE N'Bình gốm%';

-- test
-- SELECT * FROM SANPHAM WHERE TENSP LIKE N'Bình gốm%';

-- cau 13
INSERT INTO CONGNHAN (MACN, HO, TEN, PHAI, NGAYSINH, MATSX)
VALUES ('CN006', N'Lê Thị', N'Lan', N'Nữ', NULL, 'TS02');

-- test
-- SELECT * FROM CONGNHAN WHERE MACN = 'CN006';