CREATE TABLE SANPHAM
(
    MASP VARCHAR(10) PRIMARY KEY,
    TENSP NVARCHAR(50),
    DVT NVARCHAR(10),
    TIENCONG DECIMAL(10,0)
);

CREATE TABLE TOSX
(
    MATSX VARCHAR(10) PRIMARY KEY,
    TENTSX NVARCHAR(50)
);

CREATE TABLE CONGNHAN
(
    MACN VARCHAR(10) PRIMARY KEY,
    HO NVARCHAR(30),
    TEN NVARCHAR(30),
    PHAI NVARCHAR(10),
    NGAYSINH DATE,
    MATSX VARCHAR(10),
    FOREIGN KEY (MATSX) REFERENCES TOSX(MATSX)
);

CREATE TABLE SANXUAT
(
    MACN VARCHAR(10),
    MASP VARCHAR(10),
    NGAY DATE,
    SOLUONG INT,
    FOREIGN KEY (MACN) REFERENCES CONGNHAN(MACN),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
    PRIMARY KEY (MACN, MASP, NGAY)
);